return {
    { "echasnovski/mini.pairs", enabled = false },
    { "lewis6991/gitsigns.nvim", enabled = false },
    { "ggandor/leap.nvim", enabled = false },
    { "rcarriga/nvim-notify", enabled = false },
    { "lukas-reineke/indent-blankline.nvim", enabled = false },
    { "nvim-neo-tree/neo-tree.nvim", enabled = false },
    { "akinsho/bufferline.nvim", enabled = false },
    { "nvim-lualine/lualine.nvim", enabled = false },
    { "Bekaboo/dropbar.nvim", enabled = false },
    { "neoclide/coc.nvim", enabled = false },
    { "folke/neodev.nvim", enabled = false },
    { "folke/neoconf.nvim", enabled = false },
    -- { "barbecue", enabled = false },
    { "luukvbaal/nnn.nvim", enabled = false },
    { "jinh0/eyeliner.nvim", enabled = false },
    { "nvim-telescope/telescope-file-browser.nvim", enabled = false },
    { "neanias/everforest-nvim", enabled = false },
    { "rktjmp/lush.nvim", enabled = false },
    { "echasnovski/mini.comment", enabled = false },
}
