return {
    { "xzbdmw/aerial.nvim", name = "aerial.nvim", branch = "lock-7c4153fd9395" },
    { "xzbdmw/cmp-nvim-lsp", name = "cmp-nvim-lsp", branch = "lock-b4751aa1b23e" },
    { "xzbdmw/dressing.nvim", name = "dressing.nvim", branch = "lock-361821e7cd8e" },
    { "xzbdmw/git-conflict.nvim", name = "git-conflict.nvim", branch = "lock-62902526096e" },
    { "xzbdmw/gitsigns.nvim", name = "gitsigns.nvim", branch = "lock-d871a72a0fa9" },
    { "xzbdmw/guess-indent.nvim", name = "guess-indent.nvim", branch = "lock-f72848a53646" },
    { "xzbdmw/mini.indentscope", name = "mini.indentscope", branch = "lock-59c13d118c9c" },
    { "xzbdmw/mini.surround", name = "mini.surround", branch = "lock-b2c9eadb0407" },
    { "xzbdmw/multicursor.nvim", name = "multicursor.nvim", branch = "lock-d2f6f857ccab" },
    { "xzbdmw/mason-lspconfig.nvim", name = "mason-lspconfig.nvim", branch = "lock-9dfcf2036c22" },
    { "xzbdmw/mason.nvim", name = "mason.nvim", branch = "lock-751b1fcbf3d3" },
    { "xzbdmw/nightfox.nvim", name = "nightfox.nvim", branch = "lock-7c36a2f41552" },
    { "xzbdmw/noice.nvim", name = "noice.nvim", branch = "lock-60ea5017d12d" },
    { "xzbdmw/nui.nvim", name = "nui.nvim", branch = "lock-f759ff4b5070" },
    { "xzbdmw/nvim-bufdel", name = "nvim-bufdel", branch = "lock-dd4e4ff68d20" },
    { "xzbdmw/nvim-lspconfig", name = "nvim-lspconfig", branch = "lock-4017739cf570" },
    { "xzbdmw/nvim-treesitter", name = "nvim-treesitter", branch = "lock-d2039fbfb309" },
    { "xzbdmw/nvim-treesitter-textobjects", name = "nvim-treesitter-textobjects", branch = "xzb" },
    { "xzbdmw/nvim-ts-context-commentstring", name = "nvim-ts-context-commentstring", branch = "lock-7ab799a9792f" },
    { "xzbdmw/quicker.nvim", name = "quicker.nvim", branch = "lock-c58148f0a190" },
    { "xzbdmw/refactoring.nvim", name = "refactoring.nvim", branch = "lock-794d1d2718ef" },
    { "xzbdmw/satellite.nvim", name = "satellite.nvim", branch = "lock-f90494e5d29d" },
    { "xzbdmw/sibling-swap.nvim", name = "sibling-swap.nvim", branch = "lock-efe1eda6b79a" },
    { "xzbdmw/smart-open.nvim", name = "smart-open.nvim", branch = "lock-6b00faaaff58" },
    { "xzbdmw/substitute.nvim", name = "substitute.nvim", branch = "lock-156f1b750bdf" },
    {
        "xzbdmw/telescope-fzf-native.nvim",
        name = "telescope-fzf-native.nvim",
        branch = "lock-9ef21b2e6bb6",
        build = vim.fn.executable("make") == 1 and "make" or nil,
    },
    { "xzbdmw/telescope-zoxide", name = "telescope-zoxide", branch = "lock-bada7b9d00a5" },
    { "xzbdmw/tokyonight.nvim", name = "tokyonight.nvim", branch = "lock-f4b415bfbce3" },
    { "xzbdmw/vim-startuptime", name = "vim-startuptime", branch = "lock-ac2cccb5be61" },
    { "xzbdmw/vim-textobj-chainmember", name = "vim-textobj-chainmember", branch = "lock-8839aeab9141" },
    { "xzbdmw/yanky.nvim", name = "yanky.nvim", branch = "lock-2d5543627264" },
}
