local bufnr = vim.api.nvim_get_current_buf()
local keymap = vim.keymap.set
keymap({ "n", "v" }, "gl", function()
    vim.cmd.RustLsp({ "hover", "actions" })
    vim.defer_fn(function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "n", true)
        vim.cmd.RustLsp({ "hover", "range" })
    end, 100)
end, { silent = true, buffer = bufnr, desc = "lsp hover in rust" })
keymap("n", "<leader>cp", function()
    vim.cmd.RustLsp("explainError")
end, { silent = true, buffer = bufnr, desc = "rust hover type info" })
keymap("n", "<C-e>", function()
    vim.cmd.RustLsp("renderDiagnostic")
    -- vim.defer_fn(function()
    --     vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-w><C-w>", true, false, true), "n", true)
    -- end, 100)
end, { silent = true, buffer = bufnr, desc = "rust render diagnostics" })
keymap({ "x" }, "<Tab>", function()
    vim.cmd.RustLsp({ "hover", "range" })
    vim.defer_fn(function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "n", true)
        vim.cmd.RustLsp({ "hover", "range" })
    end, 100)
end, { silent = true, buffer = bufnr, desc = "rust hover range" })
keymap({ "n", "i" }, "<f4>", function()
    vim.cmd.RustLsp("runnables")
end, { silent = true, buffer = bufnr, desc = "rust runable" })
keymap({ "n", "i" }, "<f6>", function()
    vim.cmd.RustLsp("testables")
end, { silent = true, buffer = bufnr, desc = "rust testables" })
-- keymap({ "n", "i" }, "<C-a>", function()
--     vim.cmd.RustLsp("codeAction")
-- end, { silent = true, buffer = bufnr, desc = "rust testables" })
keymap({ "n" }, "<leader><leader>r", function()
    vim.cmd.RustLsp({ "runnables", bang = true })
end, { silent = true, buffer = bufnr, desc = "resume rust testables" })
keymap({ "n" }, "<leader><leader>t", function()
    vim.cmd.RustLsp({ "testables", bang = true })
end, { silent = true, buffer = bufnr, desc = "resume rust testables" })
